blank_issues_enabled: false
contact_links:
  - name: Troubleshooting guide
    url: https://react-tooltip.com/docs/troubleshooting
    about: Check the troubleshooting guide before opening a bug report.
