name: Beta Release

on:
  workflow_call:

jobs:
  beta_release:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dev dependencies
        run: yarn install

      - name: Setup npm credentials file
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> .npmrc

      - name: Setup git credentials
        run: |
          git config --global user.name 'danielbarion'
          git config --global user.email 'danielbarionn@gmail.com'

      - name: Get current package.json version
        run: echo "PACKAGE_VERSION=$(npm pkg get version)" >> $GITHUB_ENV

      - name: First beta release for this pull request
        if: contains(env.PACKAGE_VERSION, 'beta') == false
        run: echo "NEW_VERSION=$(npm version prerelease --no-git-tag-version --preid=beta.$GITHUB_PR_NUMBER)" >> $GITHUB_ENV
        env:
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Subsequent beta releases for this pull request
        if: contains(env.PACKAGE_VERSION, 'beta')
        run: echo "NEW_VERSION=$(npm version prerelease --no-git-tag-version --preid=beta)" >> $GITHUB_ENV
        env:
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Release a new beta version
        run: npm publish --tag beta
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Save new release version
        run: |
          git add ./package.json
          git commit -m "chore: bump version to $NEW_VERSION"
          git push

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Beta version released with the last commit 🚀

              \`\`\`
              yarn add react-tooltip@${{ env.NEW_VERSION }}
              \`\`\`
              or
              \`\`\`
              npm install react-tooltip@${{ env.NEW_VERSION }}
              \`\`\`
              `
            })
