name: Bundlesize

on:
  workflow_call:

jobs:
  bundlesize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dev dependencies
        run: yarn install

      - name: Build ReactTooltip component package
        run: yarn build

      - name: Bundlesize
        run: yarn run bundlesize
