name: CI
on:
  pull_request:
  push:
    branches: [master]
jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./yarn.lock') }}
      - name: npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn eslint
      - name: Test
        run: yarn test:unit
