name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dev dependencies
        run: yarn install

      - name: ESLint
        run: yarn run eslint

  test:
    needs: lint
    strategy:
      matrix:
        react-version: ['16.14', '17', '18', '19']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dev dependencies
        run: yarn install

      - name: Configure React version
        run: yarn ci:react-version ${{ matrix.react-version }}

      - name: Run tests
        run: yarn test --runInBand

      - name: Generate types
        run: npm run types
