name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dev dependencies
        run: yarn install

      - name: ESLint
        run: yarn run eslint

  test:
    needs: lint
    strategy:
      matrix:
        version: [16, 18, 20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Install dev dependencies
        run: yarn install

      - name: Run tests
        run: yarn run test
