name: Pull request workflow

on:
  push:
    branches:
      - '!master'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint:
    if: 'github.event.pull_request.draft == false'
    uses: ./.github/workflows/lint.yaml

  bundlesize:
    if: 'github.event.pull_request.draft == false'
    uses: ./.github/workflows/bundlesize.yaml

  fail_if_pull_request_is_draft:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-18.04
    steps:
      - name: Fails in order to indicate that pull request needs to be marked as ready to review and unit tests workflow needs to pass.
        run: exit 1
